default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: mspoc_todo_development
  username: postgres
  host: postgres
  # password:
  port: 5432
test:
  <<: *default
  database: mspoc-todo_test
  host: localhost
  username: postgres
production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { } %>
  username: <%= ENV.fetch("DATABASE_USER") { } %>
  # password: <%= ENV.fetch("DATABASE_PASSWORD") { } %>
  host: <%= ENV.fetch("DATABASE_URL") { } %>
  port: <%= ENV.fetch("DATABASE_PORT") { } %>
